#!/bin/bash
echo "# DataScienceTools-Project" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:Martell0x1/DataScienceTools-Project.git
git push -u origin main
